### ISSUE TITLE
What is this problem in TransAE? 

### ISSUE THREAD

**Issue by luisrui** [OpenBGBenchmark/OpenBG-IMG#1]
I have face the same problem when running the code both in TransE and in TranAE which exactly is "bash scripts/train.sh"
![image](https://github.com/OpenBGBenchmark/OpenBG-IMG/assets/72402625/7a13cb72-476b-422b-a181-e22cb6326c55)
There is no problem when running other shell scripts.
Thank you!

**Comment by TimelordRi** [comment]
Hi,
Your screenshot shows two errors, the first error means you should run `bash scripts/make.sh` in `OpenBG-IMG/TransE` and `OpenBG-IMG/TransAE` to obtain `Base.so`. After running, you can find `Base.so` in `TransE/release` and `TransAE/release`. The second error means the failure of the previous command lines. You can also debug it by running `bash scripts/make.sh`.

**Comment by luisrui** [comment]
Thank you for your reply. And I check the code here in the make.sh, it seems that it's gonna generate a Base.so in OpenKE/openke/release?
![image](https://github.com/OpenBGBenchmark/OpenBG-IMG/assets/72402625/df988761-e457-400c-9e20-1ac491767bb8)
Do I miss something that should be implemented?

**Comment by TimelordRi** [comment]
Sorry, I have no idea which file you means. 
In `TransAE/scripts/make.sh`, we do generate `Base.so` to dir `TransAE/release/`, please check the following line:
https://github.com/OpenBGBenchmark/OpenBG-IMG/blob/9c972a9dc0c431a44d5548bb1dd8f61add0cc9d2/TransAE/scripts/make.sh#L4
Note that in `TransE/scripts/make.sh` (not Trans**A**E), we compile `Base.so` to dir `OpenKE/openke/release/`, and then use the module in `TransE/train_transe.py`.

**Comment by luisrui** [comment]
Oh, it works. Thank you for your reply. I really appreciate it.
